CharacterId: 10120
translator: ""
title:
  - TextJp: 1時間目「特別講義：手段」
    TextCn: ""
    TextKr: "특별 강의: 스틱"
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1012002
    FavorScheduleId: 101202
    CharacterId: 10120
  - TextJp: 2時間目「課外授業：芸術」
    TextCn: ""
    TextKr: "외부 견학: 예술과 팝콘"
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1012003
    FavorScheduleId: 101203
    CharacterId: 10120
  - TextJp: 3時間目「清掃：招かれざる客」
    TextCn: ""
    TextKr: 불청객과 환영객
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1012005
    FavorScheduleId: 101205
    CharacterId: 10120
  - TextJp: 放課後「鼓動」
    TextCn: ""
    TextKr: 새벽의 북소리
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1012006
    FavorScheduleId: 101206
    CharacterId: 10120
content:
  - MessageKR: 망치를 쥐면
    MessageJP: ハンマーを握ると
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200010
    Id: 101200010
    CharacterId: 10120
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 세상 모든 문제가 못으로 보이는 법.
    MessageJP: 世のすべてが釘に見え
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200020
    Id: 101200020
    CharacterId: 10120
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200030
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 드럼 스틱을 쥐니
    MessageJP: ドラムスティックを握れば
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200030
    Id: 101200030
    CharacterId: 10120
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200040
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 세상 모든 게 두들길 것으로 보이네.
    MessageJP: 世のすべてがドラムに見えてくる
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200030
    Id: 101200040
    CharacterId: 10120
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200040
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: …혹시 스트레스를 풀 뭔가가 필요한 거야?
    MessageJP: ……ストレス溜まってる？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200040
    Id: 101200050
    CharacterId: 10120
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200050
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 혹시 뭔가 두들길 게 필요한 거야……?
    MessageJP: 練習大変……？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200040
    Id: 101200060
    CharacterId: 10120
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200050
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아냐 아냐, 선생님.
    MessageJP: ノンノン
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200050
    Id: 101200070
    CharacterId: 10120
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200060
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 이것은 ‘드러머’ 유토리 나츠로서의 감상.
    MessageJP: これは「ドラマー」柚鳥ナツの感想
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200050
    Id: 101200080
    CharacterId: 10120
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 하지만 스트레스 해소라는 핑계도 좋은 것 같군.
    MessageJP: ……だけど、それも悪くないかも
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200060
    Id: 101200090
    CharacterId: 10120
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200070
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그러니까 그 가게 앞에서 보자고.
    MessageJP: じゃあ、例のお店に集合～
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200060
    Id: 101200100
    CharacterId: 10120
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200070
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 네?
    MessageJP: え？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200070
    Id: 101200110
    CharacterId: 10120
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 101202
    NextGroupId: 101200080
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 예술이 인생을 모방하는 것이 아니라
    MessageJP: 芸術が人生なのではない
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200080
    Id: 101200120
    CharacterId: 10120
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 101200070
    PreConditionFavorScheduleId: 101202
    FavorScheduleId: 0
    NextGroupId: 101200090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 인생이 예술을 모방하는 것.
    MessageJP: 人生が芸術なのだ
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200090
    Id: 101200130
    CharacterId: 10120
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그런 의미에서 견학이 필요해 선생님.
    MessageJP: 時には他の芸術に触れることも肝要……
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200100
    Id: 101200140
    CharacterId: 10120
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그러니까 그 영화관 앞에서 보자고.
    MessageJP: じゃあ、映画館に集合～
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200110
    Id: 101200150
    CharacterId: 10120
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 네?
    MessageJP: え？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200120
    Id: 101200160
    CharacterId: 10120
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 101203
    NextGroupId: 101200130
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아
    MessageJP: あ
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200130
    Id: 101200170
    CharacterId: 10120
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 101200120
    PreConditionFavorScheduleId: 101203
    FavorScheduleId: 0
    NextGroupId: 101200140
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아ㅏㅏ아아ㅏ아
    MessageJP: まはやさあさ
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200140
    Id: 101200180
    CharacterId: 10120
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200150
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생니ㅁ. 긴급. 연
    MessageJP: せんうせたやく
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200150
    Id: 101200190
    CharacterId: 10120
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200160
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 연습실로
    MessageJP: れんしゅっ室
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200150
    Id: 101200200
    CharacterId: 10120
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200160
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 빨리
    MessageJP: はやく
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200150
    Id: 101200210
    CharacterId: 10120
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200160
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 어?!
    MessageJP: え！？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200160
    Id: 101200220
    CharacterId: 10120
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 101205
    NextGroupId: 101200170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 힘을 내기 위해서
    MessageJP: 力を出すために
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200170
    Id: 101200230
    CharacterId: 10120
    MessageCondition: FavorRankUp
    ConditionValue: 6
    PreConditionGroupId: 101200160
    PreConditionFavorScheduleId: 101205
    FavorScheduleId: 0
    NextGroupId: 101200180
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 힘을 빼야 한다니
    MessageJP: 力を抜かなければならないなんて
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200180
    Id: 101200240
    CharacterId: 10120
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200190
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 이 안티노미 또한 드러머가 짊어져야 할 숙명인 것일까……
    MessageJP: このアンチノミーも、ドラマーの背負うべき宿命なのか……
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200190
    Id: 101200250
    CharacterId: 10120
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101200200
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: ……?
    MessageJP: え……？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101200200
    Id: 101200260
    CharacterId: 10120
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 101206
    NextGroupId: 0
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
